package com.example.quiz.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * Represents a quiz session entity. Each instance of this class represents a single quiz session
 * for a user. It contains information about the user, the total number of questions attempted,
 * the number of correct answers, and the number of incorrect answers.
 */
@Entity
@Getter
@Setter
public class QuizSession {
    /**
     * The unique identifier for the quiz session. This field is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user associated with this quiz session. This field is a foreign key to the User entity.
     */
    @ManyToOne
    private User user;

    /**
     * The total number of questions attempted in this quiz session.
     */
    private int totalQuestions;

    /**
     * The number of correct answers given by the user in this quiz session.
     */
    private int correctAnswers;

    /**
     * The number of incorrect answers given by the user in this quiz session.
     */
    private int incorrectAnswers;
}


